on:
  webhook:
jobs:
  request:
    name: Make a HTTP Request
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          method: ${{ on.webhook.outputs.method }}
          body: ${{ toJson(on.webhook.outputs.body) }}
          headers: ${{ toJson(on.webhook.outputs.headers) }}
        run: |
          echo method: $method
          echo headers $headers
          echo body: $body
    steps:
      - name: Make a HTTP Request
        uses: actionsflow/axios@v1
        id: info
        with:
          url: https://api.netlify.com/build_hooks/${{ secrets.NETLIFYKEY }}?trigger_branch=main&trigger_title=gaction
          method: POST
          body: |
            {
              "link":"test", 
            }
